name: Deploy AVD Session Host Replacer to NIH Test

on:
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    # - uses: actions/checkout@v4
    #   with:
    #     ref: init-changes

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    # - name: Deploy Bicep file
    #   uses: azure/arm-deploy@v2
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     region: eastus
    #     template: ./workload/bicep/deploy-baseline-arpah.bicep
    #     parameters: ./workload/bicep/parameters/deploy-baseline-parameters-arpah.json avdWorkloadSubsId=${{ secrets.AZURE_SUBID_TEST }} avdVmLocalUserName=${{ secrets.AVD_ADMIN }} avdVmLocalUserPassword=${{ secrets.AVD_ADMINPASS }} avdEnterpriseAppObjectId=${{ secrets.AZURE_AVD_OBJECTID }} existingVnetAvdSubnetResourceId=${{ secrets.AZURE_VPCSUBID_TEST }} existingVnetPrivateEndpointSubnetResourceId=${{ secrets.AZURE_VPCSUBID_TEST }} identityDomainName=${{ secrets.AD_NAME}} avdDomainJoinUserName=${{ secrets.AD_JOIN_USER }} avdDomainJoinUserPassword=${{ secrets.AD_JOIN_PASS }} avdOuPath="${{ secrets.AD_OU_TEST }}"
    #     failOnStdErr: false
    
    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v2
      with:
        inlineScript: ./.github/workflows/scripts/Deploy-To-Test.ps1 -DomJoinUserName '${{ secrets.AD_JOIN_USER }}' -DomJoinUserPassword '${{ secrets.AD_JOIN_PASS }}' -OUName '${{ secrets.AD_OU_TEST }}' -SubnetId '${{ secrets.AZURE_SUBNET_ID }}' -LogAnalyticsWorkspaceId '${{ secrets.AZURE_LOGANALYTICS_WORKSPACE_ID }}' -IdentityDomainName '${{ secrets.AD_NAME}}' -ResourceGroupName '${{ secrets.HOST_POOL_RG }}' -SessionHostResourceGroupName '${{ secrets.SESSION_HOST_RG }}' -HostPoolName '${{ secrets.HOST_POOL_NAME }}' -LocalAdminUserName '${{ secrets.LOCAL_ADMIN_USER }}'
        azPSVersion: "latest"
        errorActionPreference: continue